name: Validação de Endpoints

on:
  workflow_dispatch:
  push:
    paths:
      - 'EndCheck/**'

jobs:
  executar-validacao:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar dependências
        run: |
          pip install requests


      - name: Rodar multichecker.py
        run: |
          python EndCheck/multichecker.py

      - name: Upload do relatório como artefato
        uses: actions/upload-artifact@v4
        with:
          name: relatorio-endpoints
          path: EndCheck/relatorio.html
